version: '3'

services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    environment:
      - REDIS_URL=${REDIS_URL}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    restart: always
    volumes:
      - ./.env:/app/.env
